// Change light/dark mode
export const CHANGE_MODE='CHANGE_MODE'

// Get Products
export const FETCH_PRODUCTS_BEGIN = 'FETCH_PRODUCTS_BEGIN'
export const RECEIVE_PRODUCTS = 'RECEIVE_PRODUCTS'
export const FETCH_SINGLE_PRODUCT = 'FETCH_SINGLE_PRODUCT'

//Stores
export const ADMIN_STORES_REQUEST = 'ADMIN_STORES_REQUEST'
export const ADMIN_STORES_SUCCESS = 'ADMIN_STORES_SUCCESS'
export const ADMIN_STORES_FAIL = 'ADMIN_STORES_FAIL'

export const ALL_STORES_REQUEST = 'ALL_STORES_REQUEST'
export const ALL_STORES_SUCCESS = 'ALL_STORES_SUCCESS'
export const ALL_STORES_FAIL = 'ALL_STORES_FAIL'

export const NEW_STORE_REQUEST = 'NEW_STORE_REQUEST'
export const NEW_STORE_SUCCESS = 'NEW_STORE_SUCCESS'
export const NEW_STORE_RESET = 'NEW_STORE_RESET'
export const NEW_STORE_FAIL = 'NEW_STORE_FAIL'

export const DELETE_STORE_REQUEST = 'DELETE_STORE_REQUEST'
export const DELETE_STORE_SUCCESS = 'DELETE_STORE_SUCCESS'
export const DELETE_STORE_RESET = 'DELETE_STORE_RESET'
export const DELETE_STORE_FAIL = 'DELETE_STORE_FAIL'

export const UPDATE_STORE_REQUEST = 'UPDATE_STORE_REQUEST'
export const UPDATE_STORE_SUCCESS = 'UPDATE_STORE_SUCCESS'
export const UPDATE_STORE_RESET = 'UPDATE_STORE_RESET'
export const UPDATE_STORE_FAIL = 'UPDATE_STORE_FAIL'

export const STORE_DETAILS_REQUEST = 'STORE_DETAILS_REQUEST'
export const STORE_DETAILS_SUCCESS = 'STORE_DETAILS_SUCCESS'
export const STORE_DETAILS_FAIL = 'STORE_DETAILS_FAIL'

export const MY_STORE_REQUEST = 'MY_STORE_REQUEST'
export const MY_STORE_SUCCESS = 'MY_STORE_SUCCESS'
export const MY_STORE_FAIL = 'MY_STORE_FAIL'


//USER
export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'

export const REGISTER_USER_REQUEST = 'REGISTER_USER_REQUEST'
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS'
export const REGISTER_USER_FAIL = 'REGISTER_USER_FAIL'

export const LOAD_USER_REQUEST = 'LOAD_USER_REQUEST'
export const LOAD_USER_SUCCESS = 'LOAD_USER_SUCCESS'
export const LOAD_USER_FAIL = 'LOAD_USER_FAIL'

export const UPDATE_PROFILE_REQUEST = 'UPDATE_PROFILE_REQUEST'
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS'
export const UPDATE_PROFILE_RESET = 'UPDATE_PROFILE_RESET'
export const UPDATE_PROFILE_FAIL = 'UPDATE_PROFILE_FAIL'

export const UPDATE_ACCOUNT_STATUS_REQUEST = 'UPDATE_ACCOUNT_STATUS_REQUEST'
export const UPDATE_ACCOUNT_STATUS_SUCCESS = 'UPDATE_ACCOUNT_STATUS_SUCCESS'
export const UPDATE_ACCOUNT_STATUS_FAIL = 'UPDATE_ACCOUNT_STATUS_FAIL'
export const UPDATE_ACCOUNT_STATUS_RESET = 'UPDATE_ACCOUNT_STATUS_RESET'

export const UPDATE_PASSWORD_REQUEST = 'UPDATE_PASSWORD_REQUEST'
export const UPDATE_PASSWORD_SUCCESS = 'UPDATE_PASSWORD_SUCCESS'
export const UPDATE_PASSWORD_RESET = 'UPDATE_PASSWORD_RESET'
export const UPDATE_PASSWORD_FAIL = 'UPDATE_PASSWORD_FAIL'

export const FORGOT_PASSWORD_REQUEST = 'FORGOT_PASSWORD_REQUEST'
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS'
export const FORGOT_PASSWORD_FAIL = 'FORGOT_PASSWORD_FAIL'


export const CONTACT_FORMULAIRE_REQUEST = 'CONTACT_FORMULAIRE_REQUEST'
export const CONTACT_FORMULAIRE_SUCCESS = 'CONTACT_FORMULAIRE_SUCCESS'
export const CONTACT_FORMULAIRE_FAIL = 'CONTACT_FORMULAIRE_FAIL'

export const NEW_PASSWORD_REQUEST = 'NEW_PASSWORD_REQUEST'
export const NEW_PASSWORD_SUCCESS = 'NEW_PASSWORD_SUCCESS'
export const NEW_PASSWORD_FAIL = 'NEW_PASSWORD_FAIL'

export const ALL_USERS_REQUEST = 'ALL_USERS_REQUEST'
export const ALL_USERS_SUCCESS = 'ALL_USERS_SUCCESS'
export const ALL_USERS_FAIL = 'ALL_USERS_FAIL'

export const USER_DETAILS_REQUEST = 'USER_DETAILS_REQUEST'
export const USER_DETAILS_SUCCESS = 'USER_DETAILS_SUCCESS'
export const USER_DETAILS_FAIL = 'USER_DETAILS_FAIL'

export const UPDATE_USER_REQUEST = 'UPDATE_USER_REQUEST'
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS'
export const UPDATE_USER_RESET = 'UPDATE_USER_RESET'
export const UPDATE_USER_FAIL = 'UPDATE_USER_FAIL'

export const DELETE_USER_REQUEST = 'DELETE_USER_REQUEST'
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS'
export const DELETE_USER_RESET = 'DELETE_USER_RESET'
export const DELETE_USER_FAIL = 'DELETE_USER_FAIL'

export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const LOGOUT_FAIL = 'LOGOUT_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'
export const CLEAR_RESPONSE = 'CLEAR_RESPONSE'
export const RESET = 'RESET'






// FILTERS
export const FILTER_CATEGORY = 'FILTER_CATEGORY'
export const FILTER_STORE = 'FILTER_STORE'
export const FILTER_PRICE = 'FILTER_PRICE'
export const FILTER_PRICE_DT = 'FILTER_PRICE_DT'
export const FILTER_PRICE_STORE = 'FILTER_PRICE_STORE '
export const FILTER_PRICE_DT_STORE  = 'FILTER_PRICE_DT_STORE '
export const SORT_BY = 'SORT_BY'
export const SORT_BY_STORE = 'SORT_BY_STORE'
export const EMPTY_FILTER='EMPTY_FILTER'
export const EMPTY_FILTER_STORE='EMPTY_FILTER_STORE'
export const CHANGE_CURRENCY = 'CHANGE_CURRENCY'


// Cart
export const ADD_TO_CART = 'ADD_TO_CART'
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART'
export const INCREMENT_QTY = 'INCREMENT_QTY'
export const DECREMENT_QTY = 'DECREMENT_QTY'
export const SAVE_SHIPPING_INFO = 'SAVE_SHIPPING_INFO'




// Order 
export const CREATE_ORDER_REQUEST = 'CREATE_ORDER_REQUEST'
export const CREATE_ORDER_SUCCESS = 'CREATE_ORDER_SUCCESS'
export const CREATE_ORDER_FAIL = 'CREATE_ORDER_FAIL'

export const MY_ORDERS_REQUEST = 'MY_ORDERS_REQUEST'
export const MY_ORDERS_SUCCESS = 'MY_ORDERS_SUCCESS'
export const MY_ORDERS_FAIL = 'MY_ORDERS_FAIL'

export const ALL_ORDERS_REQUEST = 'ALL_ORDERS_REQUEST'
export const ALL_ORDERS_SUCCESS = 'ALL_ORDERS_SUCCESS'
export const ALL_ORDERS_FAIL = 'ALL_ORDERS_FAIL'

export const UPDATE_ORDER_REQUEST = 'UPDATE_ORDER_REQUEST'
export const UPDATE_ORDER_SUCCESS = 'UPDATE_ORDER_SUCCESS'
export const UPDATE_ORDER_RESET = 'UPDATE_ORDER_RESET'
export const UPDATE_ORDER_FAIL = 'UPDATE_ORDER_FAIL'

export const DELETE_ORDER_REQUEST = 'DELETE_ORDER_REQUEST'
export const DELETE_ORDER_SUCCESS = 'DELETE_ORDER_SUCCESS'
export const DELETE_ORDER_RESET = 'DELETE_ORDER_RESET'
export const DELETE_ORDER_FAIL = 'DELETE_ORDER_FAIL'

export const ORDER_DETAILS_REQUEST = 'ORDER_DETAILS_REQUEST'
export const ORDER_DETAILS_SUCCESS = 'ORDER_DETAILS_SUCCESS'
export const ORDER_DETAILS_FAIL = 'ORDER_DETAILS_FAIL'







// CheckOut Process
export const CHECKOUT_REQUEST = 'CHECKOUT_REQUEST'
export const CHECKOUT_SUCCESS = 'CHECKOUT_SUCCESS'
export const CHECKOUT_FAILURE = 'CHECKOUT_FAILURE'



// News Letter
export const SUBSCRIBE_TO_NEWSLETTER_REQUEST = 'SUBSCRIBE_TO_NEWSLETTER_REQUEST'
export const SUBSCRIBE_TO_NEWSLETTER_SUCCESS = 'SUBSCRIBE_TO_NEWSLETTER_SUCCESS'
export const SUBSCRIBE_TO_NEWSLETTER_FAIL = 'SUBSCRIBE_TO_NEWSLETTER_FAIL'


