// Cart
export const ADD_TO_CART = 'ADD_TO_CART'
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART'
export const INCREMENT_QTY = 'INCREMENT_QTY'
export const DECREMENT_QTY = 'DECREMENT_QTY'
export const CLEAR_RESPONSE = 'CLEAR_RESPONSE'
export const SAVE_SHIPPING_INFO = 'SAVE_SHIPPING_INFO'

