//add product

export const NEW_PRODUCT_REQUEST = 'NEW_PRODUCT_REQUEST'
export const NEW_PRODUCT_SUCCESS = 'NEW_PRODUCT_SUCCESS'
export const NEW_PRODUCT_FAIL = 'NEW_PRODUCT_FAIL'

//the store get it's products

export const GET_STORE_PRODUCTS_REQUEST = 'GET_STORE_PRODUCTS_REQUEST'
export const GET_STORE_PRODUCTS_SUCCESS = 'GET_STORE_PRODUCTS_SUCCESS'
export const GET_STORE_PRODUCTS_FAIL = 'GET_STORE_PRODUCTS_FAIL'

//get a specifc product for a specific store

export const GET_STORE_PRODUCT_REQUEST = 'GET_STORE_PRODUCT_REQUEST'
export const GET_STORE_PRODUCT_SUCCESS = 'GET_STORE_PRODUCT_SUCCESS'
export const GET_STORE_PRODUCT_FAIL = 'GET_STORE_PRODUCT_FAIL'

//search for a specific product

export const SEARCH_PRODUCT_REQUEST = 'SEARCH_PRODUCT_REQUEST'
export const SEARCH_PRODUCT_SUCCESS = 'SEARCH_PRODUCT_SUCCESS'
export const SEARCH_PRODUCT_FAIL = 'SEARCH_PRODUCT_FAIL'

//get top products

export const TOP_PRODUCTS_REQUEST = 'TOP_PRODUCTS_REQUEST'
export const TOP_PRODUCTS_SUCCESS = 'TOP_PRODUCTS_SUCCESS'
export const TOP_PRODUCTS_FAIL = 'TOP_PRODUCTS_FAIL'

//get new products

export const NEW_PRODUCTS_REQUEST = 'NEW_PRODUCTS_REQUEST'
export const NEW_PRODUCTS_SUCCESS = 'NEW_PRODUCTS_SUCCESS'
export const NEW_PRODUCTS_FAIL = 'NEW_PRODUCTS_FAIL'

//get all products

export const GET_ALL_PRODUCTS_REQUEST = 'GET_ALL_PRODUCTS_REQUEST'
export const GET_ALL_PRODUCTS_SUCCESS = 'GET_ALL_PRODUCTS_SUCCESS'
export const GET_ALL_PRODUCTS_FAIL = 'GET_ALL_PRODUCTS_FAIL'

//a store updates a single product

export const UPDATE_PRODUCT_REQUEST = 'UPDATE_PRODUCT_REQUEST'
export const UPDATE_PRODUCT_SUCCESS = 'UPDATE_PRODUCT_SUCCESS'
export const UPDATE_PRODUCT_FAIL = 'UPDATE_PRODUCT_FAIL'

//a store updates a single product details

export const UPDATE_PRODUCT_DETAIL_REQUEST = 'UPDATE_PRODUCT_DETAIL_REQUEST'
export const UPDATE_PRODUCT_DETAIL_SUCCESS = 'UPDATE_PRODUCT_DETAIL_SUCCESS'
export const UPDATE_PRODUCT_DETAIL_FAIL = 'UPDATE_PRODUCT_DETAIL_FAIL'

//the store can delete a specific product

export const DELETE_PRODUCT_REQUEST = 'DELETE_PRODUCT_REQUEST'
export const DELETE_PRODUCT_SUCCESS = 'DELETE_PRODUCT_SUCCESS'
export const DELETE_PRODUCT_FAIL = 'DELETE_PRODUCT_FAIL'

//the admin can delete a specific product

export const DELETE_ADMIN_PRODUCT_REQUEST = 'DELETE_ADMIN_PRODUCT_REQUEST'
export const DELETE_ADMIN_PRODUCT_SUCCESS = 'DELETE_ADMIN_PRODUCT_SUCCESS'
export const DELETE_ADMIN_PRODUCT_FAIL = 'DELETE_ADMIN_PRODUCT_FAIL'

//the admin can get all products for all stores

export const GET_ADMIN_PRODUCTS_REQUEST = 'GET_ADMIN_PRODUCTS_REQUEST'
export const GET_ADMIN_PRODUCTS_SUCCESS = 'GET_ADMIN_PRODUCTS_SUCCESS'
export const GET_ADMIN_PRODUCTS_FAIL = 'GET_ADMIN_PRODUCTS_FAIL'

//the user creates a review for a product

export const NEW_REVIEW_REQUEST = 'NEW_REVIEW_REQUEST'
export const NEW_REVIEW_SUCCESS = 'NEW_REVIEW_SUCCESS'
export const NEW_REVIEW_FAIL = 'NEW_REVIEW_FAIL'

//the admin can get all the reviews

export const GET_ADMIN_REVIEWS_REQUEST = 'GET_ADMIN_REVIEWS_REQUEST'
export const GET_ADMIN_REVIEWS_SUCCESS = 'GET_ADMIN_REVIEWS_SUCCESS'
export const GET_ADMIN_REVIEWS_FAIL = 'GET_ADMIN_REVIEWS_FAIL'

// get the reviews of a specific product

export const GET_PRODUCT_REVIEWS_REQUEST = 'GET_ADMIN_PRODUCT_REVIEWS_REQUEST'
export const GET_PRODUCT_REVIEWS_SUCCESS = 'GET_ADMIN_PRODUCT_REVIEWS_SUCCESS'
export const GET_PRODUCT_REVIEWS_FAIL = 'GET_ADMIN_PRODUCT_REVIEWS_FAIL'

//the user can delete his review

export const DELETE_REVIEW_REQUEST = 'DELETE_REVIEW_REQUEST'
export const DELETE_REVIEW_SUCCESS = 'DELETE_REVIEW_SUCCESS'
export const DELETE_REVIEW_FAIL = 'DELETE_REVIEW_FAIL'

//the admin can delete a specific review

export const DELETE_ADMIN_REVIEW_REQUEST = 'DELETE_ADMIN_REVIEW_REQUEST'
export const DELETE_ADMIN_REVIEW_SUCCESS = 'DELETE_ADMIN_REVIEW_SUCCESS'
export const DELETE_ADMIN_REVIEW_FAIL = 'DELETE_ADMIN_REVIEW_FAIL'

//the user can update a specific review

export const UPDATE_REVIEW_REQUEST = 'UPDATE_REVIEW_REQUEST'
export const UPDATE_REVIEW_SUCCESS = 'UPDATE_REVIEW_SUCCESS'
export const UPDATE_REVIEW_FAIL = 'UPDATE_REVIEW_FAIL'

//clear errors

export const CLEAR_ERRORS='CLEAR_ERRORS'

//get store name

export const GET_STORE_NAME_REQUEST = 'GET_STORE_NAME_REQUEST'
export const GET_STORE_NAME_SUCCESS = 'GET_STORE_NAME_SUCCESS'
export const GET_STORE_NAME_FAIL = 'GET_STORE_NAME_FAIL'


export const CHANGE_CURRENCY = 'CHANGE_CURRENCY'





