//add product

export const NEW_PRODUCT_REQUEST = 'NEW_PRODUCT_REQUEST'
export const NEW_PRODUCT_SUCCESS = 'NEW_PRODUCT_SUCCESS'
export const NEW_PRODUCT_FAIL = 'NEW_PRODUCT_FAIL'

//get products for a specific store

export const GET_STORE_PRODUCTS_REQUEST = 'GET_STORE_PRODUCTS_REQUEST'
export const GET_STORE_PRODUCTS_SUCCESS = 'GET_STORE_PRODUCTS_SUCCESS'
export const GET_STORE_PRODUCTS_FAIL = 'GET_STORE_PRODUCTS_FAIL'

//get a specifc product for a specific store

export const GET_STORE_PRODUCT_REQUEST = 'GET_STORE_PRODUCT_REQUEST'
export const GET_STORE_PRODUCT_SUCCESS = 'GET_STORE_PRODUCT_SUCCESS'
export const GET_STORE_PRODUCT_FAIL = 'GET_STORE_PRODUCT_FAIL'

//search for a specific product

export const SEARCH_PRODUCT_REQUEST = 'SEARCH_PRODUCT_REQUEST'
export const SEARCH_PRODUCT_SUCCESS = 'SEARCH_PRODUCT_SUCCESS'
export const SEARCH_PRODUCT_FAIL = 'SEARCH_PRODUCT_FAIL'

//get top products

export const GET_TOP_PRODUCTS_REQUEST = 'GET_TOP_PRODUCTS_REQUEST'
export const GET_TOP_PRODUCTS_SUCCESS = 'GET_TOP_PRODUCTS_SUCCESS'
export const GET_TOP_PRODUCTS_FAIL = 'GET_TOP_PRODUCTS_FAIL'

//get new products

export const GET_NEW_PRODUCTS_REQUEST = 'GET_NEW_PRODUCTS_REQUEST'
export const GET_NEW_PRODUCTS_SUCCESS = 'GET_NEW_PRODUCTS_SUCCESS'
export const GET_NEW_PRODUCTS_FAIL = 'GET_NEW_PRODUCTS_FAIL'

//get all products

export const GET_ALL_PRODUCTS_REQUEST = 'GET_ALL_PRODUCTS_REQUEST'
export const GET_ALL_PRODUCTS_SUCCESS = 'GET_ALL_PRODUCTS_SUCCESS'
export const GET_ALL_PRODUCTS_FAIL = 'GET_ALL_PRODUCTS_FAIL'

//a store updates a single product

export const UPDATE_PRODUCT_REQUEST = 'UPDATE_PRODUCT_REQUEST'
export const UPDATE_PRODUCT_SUCCESS = 'UPDATE_PRODUCT_SUCCESS'
export const UPDATE_PRODUCT_FAIL = 'UPDATE_PRODUCT_FAIL'

//the store can delete a specific product

export const DELETE_PRODUCT_REQUEST = 'DELETE_PRODUCT_REQUEST'
export const DELETE_PRODUCT_SUCCESS = 'DELETE_PRODUCT_SUCCESS'
export const DELETE_PRODUCT_FAIL = 'DELETE_PRODUCT_FAIL'

//the store can delete a specific product

export const DELETE_PRODUCT_REQUEST = 'DELETE_PRODUCT_REQUEST'
export const DELETE_PRODUCT_SUCCESS = 'DELETE_PRODUCT_SUCCESS'
export const DELETE_PRODUCT_FAIL = 'DELETE_PRODUCT_FAIL'

//the admin can get all products for all stores

export const GET_ADMIN_PRODUCTS_REQUEST = 'GET_ADMIN_PRODUCTS_REQUEST'
export const GET_ADMIN_PRODUCTS_SUCCESS = 'GET_ADMIN_PRODUCTS_SUCCESS'
export const GET_ADMIN_PRODUCTS_FAIL = 'GET_ADMIN_PRODUCTS_FAIL'

//the admin gets a specifc product for a specific store

export const GET_ADMIN_STORE_PRODUCT_REQUEST = 'GET_ADMIN_STORE_PRODUCT_REQUEST'
export const GET_ADMIN_STORE_PRODUCT_SUCCESS = 'GET_ADMIN_STORE_PRODUCT_SUCCESS'
export const GET_ADMIN_STORE_PRODUCT_FAIL = 'GET_ADMIN_STORE_PRODUCT_FAIL'

//the admin can get a specific product

export const GET_ADMIN_PRODUCT_REQUEST = 'GET_ADMIN_PRODUCT_REQUEST'
export const GET_ADMIN_PRODUCT_SUCCESS = 'GET_ADMIN_PRODUCT_SUCCESS'
export const GET_ADMIN_PRODUCT_FAIL = 'GET_ADMIN_PRODUCT_FAIL'

//the admin can get all the reviews

export const GET_ADMIN_REVIEWS_REQUEST = 'GET_ADMIN_REVIEWS_REQUEST'
export const GET_ADMIN_REVIEWS_SUCCESS = 'GET_ADMIN_REVIEWS_SUCCESS'
export const GET_ADMIN_REVIEWS_FAIL = 'GET_ADMIN_REVIEWS_FAIL'

//the admin gets the reviews of a specific product

export const GET_ADMIN_PRODUCT_REVIEWS_REQUEST = 'GET_ADMIN_PRODUCT_REVIEWS_REQUEST'
export const GET_ADMIN_PRODUCT_REVIEWS_SUCCESS = 'GET_ADMIN_PRODUCT_REVIEWS_SUCCESS'
export const GET_ADMIN_PRODUCT_REVIEWS_FAIL = 'GET_ADMIN_PRODUCT_REVIEWS_FAIL'




